[package]
name = "enum-debug-derive"
version = "0.2.0"
edition = "2021"
authors = [ "Lut99" ]
description = "Implements `#[derive(EnumDebug)]` for the `enum-debug` crate."

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn   = { version = "1.0", features = ["derive"] }
